#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI

on:
  schedule:
    - cron: 0 0 1 * *
  push:
    branches: 
      - master

jobs:
  build_openwrt:
    name: Build OpenWrt and release
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h
          
      - name: Add AdGuardhome
        run: |
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git ./package/lean/luci-app-adguardhome

      - name: Update feeds
        run: |
          #修改LAN口地址
          sed -i 's/192.168.1.1/172.31.0.10/g' ./package/base-files/files/bin/config_generate
          
          sed -i 's/\"#src-git\"/\"src-git\"/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          # X86_64 固件配置
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_ARIA2_BITTORRENT=y
          CONFIG_ARIA2_NOXML=y
          CONFIG_ARIA2_OPENSSL=y
          CONFIG_ARIA2_WEBSOCKET=y
          CONFIG_OCSERV_HTTP_PARSER=y
          CONFIG_OCSERV_PROTOBUF=y
          CONFIG_OPENCONNECT_GNUTLS=y
          CONFIG_PACKAGE_6in4=y
          # CONFIG_PACKAGE_amule is not set
          CONFIG_PACKAGE_aria2=y
          CONFIG_PACKAGE_ariang=y
          # CONFIG_PACKAGE_boost-chrono is not set
          # CONFIG_PACKAGE_boost-random is not set
          CONFIG_PACKAGE_certtool=y
          # CONFIG_PACKAGE_icu is not set
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kcptun-client=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-sit=y
          # CONFIG_PACKAGE_libbfd is not set
          # CONFIG_PACKAGE_libcryptopp is not set
          # CONFIG_PACKAGE_libdb47 is not set
          # CONFIG_PACKAGE_libdouble-conversion is not set
          # CONFIG_PACKAGE_libffi is not set
          # CONFIG_PACKAGE_liblzma is not set
          # CONFIG_PACKAGE_liblzo is not set
          # CONFIG_PACKAGE_libminiupnpc is not set
          # CONFIG_PACKAGE_libnatpmp is not set
          # CONFIG_PACKAGE_libpcre2-16 is not set
          # CONFIG_PACKAGE_libpng is not set
          # CONFIG_PACKAGE_libupnp is not set
          # CONFIG_PACKAGE_libwxbase is not set
          # CONFIG_PACKAGE_libzstd is not set
          CONFIG_PACKAGE_luci-app-adguardhome=y
          # CONFIG_PACKAGE_luci-app-amule is not set
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-netdata=y
          CONFIG_PACKAGE_luci-app-ocserv=y
          # CONFIG_PACKAGE_luci-app-openvpn-server is not set
          # CONFIG_PACKAGE_luci-app-qbittorrent is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-watchcat=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-netdata-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-watchcat-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-webadmin-zh-cn=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-openconnect=y
          CONFIG_PACKAGE_netdata=y
          CONFIG_PACKAGE_ocserv=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_openconnect=y
          # CONFIG_PACKAGE_openvpn-easy-rsa is not set
          # CONFIG_PACKAGE_openvpn-openssl is not set
          # CONFIG_PACKAGE_python3 is not set
          # CONFIG_PACKAGE_python3-asyncio is not set
          # CONFIG_PACKAGE_python3-base is not set
          # CONFIG_PACKAGE_python3-cgi is not set
          # CONFIG_PACKAGE_python3-cgitb is not set
          # CONFIG_PACKAGE_python3-codecs is not set
          # CONFIG_PACKAGE_python3-ctypes is not set
          # CONFIG_PACKAGE_python3-dbm is not set
          # CONFIG_PACKAGE_python3-decimal is not set
          # CONFIG_PACKAGE_python3-distutils is not set
          # CONFIG_PACKAGE_python3-email is not set
          # CONFIG_PACKAGE_python3-gdbm is not set
          # CONFIG_PACKAGE_python3-light is not set
          # CONFIG_PACKAGE_python3-logging is not set
          # CONFIG_PACKAGE_python3-lzma is not set
          # CONFIG_PACKAGE_python3-multiprocessing is not set
          # CONFIG_PACKAGE_python3-ncurses is not set
          # CONFIG_PACKAGE_python3-openssl is not set
          # CONFIG_PACKAGE_python3-pydoc is not set
          # CONFIG_PACKAGE_python3-sqlite3 is not set
          # CONFIG_PACKAGE_python3-unittest is not set
          # CONFIG_PACKAGE_python3-urllib is not set
          # CONFIG_PACKAGE_python3-xml is not set
          # CONFIG_PACKAGE_qBittorrent is not set
          # CONFIG_PACKAGE_qt5-core is not set
          # CONFIG_PACKAGE_qt5-network is not set
          # CONFIG_PACKAGE_qt5-xml is not set
          # CONFIG_PACKAGE_rblibtorrent is not set
          CONFIG_PACKAGE_vpnc-scripts=y
          CONFIG_PACKAGE_watchcat=y
          # CONFIG_PACKAGE_zerotier is not set
          CONFIG_KERNEL_BUILD_USER="LostNetwork"
          CONFIG_GRUB_TITLE="OpenWrt AutoBuild by LostNetwork"
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
